services:
  nginx:
    image: nginx
    container_name: nginx
    network_mode: host
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
