services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    environment:
      - EUREKA_HOST=${EUREKA_HOST}
      - CONFIG_HOST=${CONFIG_HOST}
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus-data: