scrape_configs:
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 60s
    static_configs:
      - targets: ['${EUREKA_HOST}:8761']
  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 60s
    static_configs:
      - targets: ['${CONFIG_HOST}:9000']