filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/app/logs/api.log
    fields:
      server_name: "xx-service"
      environment: "dev"
      log_type: api
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /var/log/app/logs/general.log
    fields:
      server_name: "xx-service"
      environment: "dev"
      log_type: general
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /var/log/app/logs/jdbc.log
    fields:
      server_name: "xx-service"
      environment: "dev"
      log_type: jdbc
    fields_under_root: true

output.logstash:
  hosts: ["${LOGSTASH_HOST}:5044"]
